# Example playbook structure.

---
- name: Initial server setup
  hosts: all_nodes
  become: yes
  tasks:
    - name: Ensure all packages are up to date
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Install a common package (e.g., htop)
      ansible.builtin.apt:
        name: htop
        state: present
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'