# This is to build out the cluster and join up all the nodes as specified.
# The first 3 nodes are 'control plane' nodes well the last two are worker nodes.

# WORK IN PROGRESS

---
# Play 1: Create the cluster
- name: Create the cluster
  hosts: k8s_control_plane[1:], k8s_workers
  become: yes
  serial: 1  # Tells the playbook to process each one individually and one at a time with a unique join token for each.
  tasks:
    - name: Generate a fresh join token for the current host
      ansible.builtin.shell: microk8s add-node
      run_once: true
      delegate_to: "{{ groups['k8s_control_plane'][0] }}" # delegates the first server in the list to act as the main Node to join all others against 
      register: token_output

    - name: Run join command
      ansible.builtin.shell: "{{ token_output.stdout | regex_search('microk8s join .*') }} --worker"  # This parses out the join command and leave out all the extra output of the command
      when: inventory_hostname in groups['k8s_workers'] # goes well items still exist in the inventory list in the workers section

    - name: Run join command for control plane
      ansible.builtin.shell: "{{ token_output.stdout | regex_search('microk8s join .*') }}" # This parses out the join command and leave out all the extra output of the command 
      when: inventory_hostname in groups['k8s_control_plane'] # goes well items still exist in the inventory list for the control plane section

# Play 2: Configure cluster add-ons
- name: Configure cluster add-ons
  hosts: k8s_control_plane[0]
  become: yes
  tasks:
    # 1. Enable metrics-server
    - name: Enable metrics-server add-on (idempotent) # operation will produce the same result every time it is run, regardless of the system's initial state.
      ansible.builtin.shell: microk8s enable metrics-server
      register: metrics_result
      # Tells Ansible it only "changed" things if it actually did an install
      changed_when: "'is already enabled' not in metrics_result.stdout"

    # 2. Enable MetalLB add-on
    - name: Enable MetalLB add-on (idempotent) # operation will produce the same result every time it is run, regardless of the system's initial state.
      ansible.builtin.shell: "microk8s enable metallb:{{metalLB_ip_range}}" # MetalLB Range for default Lan of test cluster - Will also need to move to a variable for environments
      register: metallb_result
      # Tells Ansible it only "changed" things if it actually did an install
      changed_when: "'is already enabled' not in metallb_result.stdout"

    # 3. Enable observability add-on
    - name: Enable observability add-on
      ansible.builtin.shell: microk8s enable observability
      register: obs_result
      # This tells Ansible it only "changed" things if it actually did an install
      changed_when: "'is already enabled' not in obs_result.stdout"

    # 4. Wait for the Grafana deployment object to be created by the add-on
    - name: Wait for Grafana deployment to exist
      ansible.builtin.shell: microk8s kubectl get deployment kube-prom-stack-grafana -n observability
      register: grafana_check
      retries: 24   # Try for up to 4 minutes (24 * 10 seconds)
      delay: 10
      until: grafana_check.rc == 0
      changed_when: false # Checking status shouldn't register as a "change"

    # 5. Scale down the built-in Grafana
    - name: Scale observability Grafana down to 0 replicas
      ansible.builtin.shell: microk8s kubectl scale deployment kube-prom-stack-grafana -n observability --replicas=0
      register: scale_result
      # kubectl outputs "... scaled" when it changes, and "... unchanged" when it's already at 0
      changed_when: "'scaled' in scale_result.stdout"