# This is to install python libraries to primary first node in order to interprate the deploy_applications.yaml

---
- name: Deployment_prep
  hosts: k8s_control_plane[0]
  become: yes

  tasks:
    # Install pip packages
    - name: Ensure python3-pip is installed
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes

    # Install Libraries
    - name: Ensure Kubernetes Python library is installed
      ansible.builtin.pip:
        name: Kubernetes
        state: present
        extra_args: "--break-system-packages"

    # Get the config for microk8s for user to use
    - name: Get MicroK8s config content
      ansible.builtin.shell: microk8s config
      register: microk8s_config_output
      changed_when: false # Do not report a change
      
     # Create the directory needed for the copy task 
    - name: Create personal .kube directory
      ansible.builtin.file:
        path: /home/levix/.kube
        state: directory  # Creates the directory
        owner: levix
        group: levix
        mode: '0700'

    # Copy the kube config to directory
    - name: Create personal .kube directory and config file for Ansible user
      ansible.builtin.copy:
        content: "{{ microk8s_config_output.stdout }}"
        dest: "/home/levix/.kube/config" # Use the actual home directory
        owner: levix
        group: levix
        mode: '0600'
        
