---
- name: DEPLOY ALL SECRETS AND MANIFESTS
  hosts: k8s_control_plane[0]
  become: yes # Needed for the initial fetch task

  # Variables are read from your inventory/command line
  
  # CRITICAL FIX: The universal environment override for all delegated tasks
  vars:
    ansible_remote_tmp: /tmp/ansible-temp

  tasks:
    # Runs ONCE per play to ensure the Kubeconfig is on the runner for the k8s module
    - name: 1. Fetch MicroK8s client config to Controller (Needed for Apply task)
      ansible.builtin.fetch:
        src: /var/snap/microk8s/current/credentials/client.config 
        dest: /tmp/kubeconfig/ 
        flat: yes 

  # The roles block is where the real work happens!
  roles:
    # 1. DEPLOY homarr-secret
    - name: "Deploy Homarr Secret"
      role: k8s_secrets_deployer
      # Variables passed to the role:
      template_src: templates/homarr-secrets.yaml.j2
      dest_filename: homarr-secret.yaml


      vars_files:
        # 'vault_environment' in inventory
        - "ansible_vault/{{ vault_environment }}/homarr-vault.yaml"
      
    # 2. DEPLOY postgre-homarr-secrets
    - name: "Deploy postgre-homarr-secrets"
      role: k8s_secrets_deployer
      # Variables passed to the role:
      template_src: templates/postgre-homarr-secrets.yaml.j2
      dest_filename: postgre-homarr-secrets.yaml

      
      vars_files:
        # 'vault_environment' in inventory
        - "ansible_vault/{{ vault_environment }}/postgre-homarr-vault.yaml"