# Role Based Playbook to add secrets to the MicroK8s Cluster.  Each role defined a secret yaml that will be applied to the Cluster.
# Templates with secrets are used to inject variables to create final yaml deployment.
# ansible_vault directory use to store secrets based on environment.
# vault_environment variable defined in inventory to signify environment.
# To add a new secret to the playbook just add another role and follow syntax

---
- name: DEPLOY ALL SECRETS AND MANIFESTS
  hosts: k8s_control_plane[0]
  become: yes # Needed for the initial fetch task
  
  # The universal environment override for all delegated tasks
  vars:
    ansible_remote_tmp: /tmp/ansible-temp

  vars_files:
        # 'environment' in inventory
        # Will need to add a new line of variable for file if a new secret is added here:
        - "ansible_vault/{{ environment }}/homarr-vault.yaml"
        - "ansible_vault/{{ environment }}/postgre-homarr-vault.yaml"

  tasks:
    # Runs ONCE per play to ensure the Kubeconfig is on the runner for the k8s module
    - name: 1. Fetch MicroK8s client config to Controller (Needed for Apply task)
      ansible.builtin.fetch:
        src: /var/snap/microk8s/current/credentials/client.config 
        dest: /tmp/kubeconfig/ 
        flat: yes 

  # Each role will run against main.yaml logic in roles/k8s_secrets_deployer/tasks - for each defined
  roles:
    # 1. DEPLOY homarr-secret
    - name: "Deploy Homarr Secret"
      role: k8s_secrets_deployer
      # Variables passed to the role:
      template_src: templates/homarr-secrets.yaml.j2
      dest_filename: homarr-secret.yaml

    # 2. DEPLOY postgre-homarr-secrets
    - name: "Deploy postgre-homarr-secrets"
      role: k8s_secrets_deployer
      # Variables passed to the role:
      template_src: templates/postgre-homarr-secrets.yaml.j2
      dest_filename: postgre-homarr-secrets.yaml

        