# Working Playbook to inject secrets via ansible vault.
# Currently working on homarr secret to how it can work and get a working sample.

---
- name: Deploy Kubernetes secret using vault variables
  # Target only the first host in the 'k8s_control_plane' group
  # The slice [0] targets the very first item (vmus-test-k8s-01)
  hosts: k8s_control_plane[0] 
  become: yes # Use 'become: yes' if the task requires root/sudo privileges

  # 1. Load your Ansible Vault file
  # The path is relative to the playbook file, 
  # so adjust if your playbook is in a different location.
  vars_files:
    - ansible_vault/dev/homar-vault.yaml

  tasks:
   # 1. FETCH KUBECONFIG TO RUNNER
    - name: Fetch MicroK8s client config to Controller
      ansible.builtin.fetch:
        src: /var/snap/microk8s/current/credentials/client.config 
        dest: /tmp/kubeconfig/ 
        flat: yes 

    # We remove the "Set HOME environment..." task, it failed.

    # 2. GENERATE MANIFEST ON RUNNER AS 'levix'
    - name: Ensure Kubernetes secret is created/updated from template (on Controller as levix)
      ansible.builtin.template:
        src: templates/55-inject-secrets.yaml.j2 
        dest: /home/levix/.kube/homar-k8s-secret.yaml 
      delegate_to: localhost 
      become: no 
      become_user: levix 
      run_once: true
      connection: local
      # NEW: EXPLICITLY FORCE REMOTE_TMP
      vars:
        ansible_remote_tmp: /tmp/ansible-temp

    # 3. APPLY SECRET USING RUNNER'S KUBECONFIG
    - name: Apply the Kubernetes secret configuration to the cluster
      kubernetes.core.k8s:
        kubeconfig: /tmp/kubeconfig/client.config 
        src: /home/levix/.kube/homar-k8s-secret.yaml
        state: present
      delegate_to: localhost 
      become: no
      become_user: levix 
      connection: local
      # NEW: EXPLICITLY FORCE REMOTE_TMP
      vars:
        ansible_remote_tmp: /tmp/ansible-temp
      register: k8s_result