# Working Playbook to inject secrets via ansible vault.
# Currently working on homarr secret to how it can work and get a working sample.

---
- name: Deploy Homarr Secret to Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false
  
  # 1. Load the encrypted variables file
  vars_files:
    - homar-vault.yaml 

  tasks:
    - name: Ensure Kubernetes Secret is created/updated
      kubernetes.core.k8s:
        state: present
        # Use 'template' parameter to render the Jinja2 file
        template: homarr-secret.yaml.j2
        # The variables from vars_files are decrypted by Ansible and injected into the template