# Inventory for camper portainer host
# For my docker deployment VM in my remote camper Proxmox host for lightweight service running.

[all:vars]
# Variables common to ALL hosts in this file
ansible_ssh_common_args='-o StrictHostKeyChecking=no' # Allows connection without pre-adding keys

[remote_docker]
10.100.100.10 ansible_user=levix
