# Non-k8s server update list

[pihole]
vmus-camp-phi-01 ansible_host=10.100.100.2

[other]
vmus-camp-ptr-01 ansible_host=10.100.100.10
vmus-camp-jlf-01  ansible_host=10.100.100.225

[all_nodes:children]
pihole
other
