# Deploy all compose files based on environment

---
- name: Deploy Stacks from External Compose Repo
  hosts: remote_docker
  become: true
  vars:
    # env_target comes from your Inventory
    remote_base_path: "/opt/appdata"
    temp_repo_path: "{{ playbook_dir }}/.temp_docker_repo"
    docker_repo_url: "https://github.com/levix1610/docker_compose.git"

  tasks:
    - name: "Local: Clone Docker Compose repo"
      delegate_to: localhost
      become: false
      git:
        repo: "{{ docker_repo_url }}"
        dest: "{{ temp_repo_path }}"
        version: main
        force: yes
      vars:
        ansible_remote_tmp: /tmp
      environment:
        HOME: /tmp

    - name: "Local: Find all compose files"
      delegate_to: localhost
      become: false
      find:
        paths: "{{ temp_repo_path }}/{{ env_target }}"
        patterns: "*.yaml,*.yml"
      register: found_compose_files
      vars:
        ansible_remote_tmp: /tmp
      environment:
        HOME: /tmp

    - name: "Ensure directory exists for each service"
      file:
        # This ensures we use the "clean" name (e.g., grafana) instead of the filename
        path: "{{ remote_base_path }}/{{ item.path | basename | regex_replace('-compose\\.(yaml|yml)$|\\.(yaml|yml)$', '') }}"
        state: directory
        owner: "1001"
        group: "1001"
        mode: '0755'
      loop: "{{ found_compose_files.files }}"

    - name: "Sync compose files to host"
      copy:
        src: "{{ item.path }}"
        dest: "{{ remote_base_path }}/{{ item.path | basename | regex_replace('\\.(yaml|yml)$', '') }}/docker-compose.yml"
      loop: "{{ found_compose_files.files }}"

    - name: "Docker Compose Up (Shell)"
      shell: "docker compose up -d"
      args:
        chdir: "{{ remote_base_path }}/{{ item.path | basename | regex_replace('\\.(yaml|yml)$', '') }}"
      loop: "{{ found_compose_files.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      environment:
        # This still passes your Homarr secret into the shell environment
        homarr_secret_key: "{{ homarr_secret_key }}"