# Inventory of servers for microk8s Cluster
# --- PROD ENVIRONMENT ---

[all:vars]
# Variables common to ALL hosts in this file
ansible_ssh_common_args='-o StrictHostKeyChecking=no' # Allows connection without pre-adding keys
ansible_user=levix
nfs_microk8s_source="10.104.104.30:/mnt/storage_pool/prod_microk8s"
metalLB_ip_range="10.104.104.15-10.104.104.25"
manifests_base_path="~/kubernetes_deployments"
manifests_path="~/kubernetes_deployments/PROD"
repo="https://github.com/levix1610/kubernetes_deployments.git"
environment="prod"


# --- HOST GROUPS DEFINITIONS ---

# This group contains all hosts for generalized tasks
[prod]
vmus-prod-k8s-[01:07]


# --- K8S ROLE DEFINITIONS ---

[k8s_control_plane]
vmus-prod-k8s-01 ansible_host=10.104.104.2 primary_node_ip=10.104.104.2
vmus-prod-k8s-02 ansible_host=10.104.104.3 primary_node_ip=10.104.104.3
vmus-prod-k8s-03 ansible_host=10.104.104.4 primary_node_ip=10.104.104.4

[k8s_workers]
vmus-prod-k8s-04 ansible_host=10.104.104.5 primary_node_ip=10.104.104.5
vmus-prod-k8s-05 ansible_host=10.104.104.6 primary_node_ip=10.104.104.6
vmus-prod-k8s-06 ansible_host=10.104.104.7 primary_node_ip=10.104.104.7
vmus-prod-k8s-07 ansible_host=10.104.104.8 primary_node_ip=10.104.104.8


# --- META GROUP: Defines a collection of other groups ---

[all_nodes:children]
k8s_control_plane
k8s_workers