# Inventory to update PROD microk8s cluster

[all:vars]
k8s_primary="vmus-prod-k8s-01"

[k8s_control]
vmus-prod-k8s-01 ansible_host=10.0.150.210
vmus-prod-k8s-02 ansible_host=10.0.150.211
vmus-prod-k8s-03 ansible_host=10.0.150.212

[k8s_workers]
vmus-prod-k8s-04 ansible_host=10.0.150.213
vmus-prod-k8s-05 ansible_host=10.0.150.214

[k8s_nodes:children]
k8s_control
k8s_workers