# Non-k8s server update list

[pihole]
vmus-prod-phi-01 ansible_host=10.0.150.2

[other]
vmus-prod-plx-01 ansible_host=10.0.150.32
vmus-prod-ssh-01 ansible_host=10.0.150.40
vmus-prod-bks-01 ansible_host=10.0.150.41
vmus-prod-jly-01 ansible_host=10.0.150.33

[all_nodes:children]
pihole
other
