# Inventory to update PROD microk8s cluster

[all:vars]
k8s_primary="vmus-prod-k8s-01"

[k8s_control_plane]
vmus-prod-k8s-01 ansible_host=10.104.104.2
vmus-prod-k8s-02 ansible_host=10.104.104.3
vmus-prod-k8s-03 ansible_host=10.104.104.4

[k8s_workers]
vmus-prod-k8s-04 ansible_host=10.104.104.5
vmus-prod-k8s-05 ansible_host=10.104.104.6
vmus-prod-k8s-06 ansible_host=10.104.104.7
vmus-prod-k8s-07 ansible_host=10.104.104.8

[all_nodes:children]
k8s_control_plane
k8s_workers