# Inventory of servers for test microk8s Cluster
# Use with microk8s test ssh-key
# Inventory used with ansible_k8s_cluster

# --- DEVELOPMENT ENVIRONMENT ---

[all:vars]
# Variables common to ALL hosts in this file
ansible_ssh_common_args='-o StrictHostKeyChecking=no' # Allows connection without pre-adding keys
ansible_user=levix
nfs_microk8s_source="10.105.105.30:/mnt/storage_pool/dev_microk8s" # Updated to synology storage
metalLB_ip_range="10.105.105.15-10.105.105.25"
manifests_base_path="~/kubernetes_deployments"
manifests_path="~/kubernetes_deployments/DEV-Microk8s"
repo="https://github.com/levix1610/kubernetes_deployments.git"
environment="dev"


# --- HOST GROUPS DEFINITIONS ---

# This group contains all hosts for generalized tasks (like common hardening)
[dev]
vmus-dev-k8s-[01:05]


# --- K8S ROLE DEFINITIONS ---

[k8s_control_plane]
vmus-dev-k8s-01 ansible_host=10.105.105.2 primary_node_ip=10.105.105.2
vmus-dev-k8s-02 ansible_host=10.105.105.3 primary_node_ip=10.105.105.3
vmus-dev-k8s-03 ansible_host=10.105.105.4 primary_node_ip=10.105.105.4

[k8s_workers]
vmus-dev-k8s-04 ansible_host=10.105.105.5 primary_node_ip=10.105.105.5
vmus-dev-k8s-05 ansible_host=10.105.105.6 primary_node_ip=10.105.105.6


# --- META GROUP: Defines a collection of other groups ---

[all_nodes:children]
k8s_control_plane
k8s_workers
