# Inventory to update DEV microk8s cluster

[all:vars]
k8s_primary="vmus-dev-k8s-01"

[k8s_control_plane]
vmus-dev-k8s-01 ansible_host=10.105.105.2
vmus-dev-k8s-02 ansible_host=10.105.105.3
vmus-dev-k8s-03 ansible_host=10.105.105.4

[k8s_workers]
vmus-dev-k8s-04 ansible_host=10.105.105.5
vmus-dev-k8s-05 ansible_host=10.105.105.6

[k8s_nodes:children]
k8s_control
k8s_workers