# This is to build out the cluster and join up all the nodes as specified.
# The first 3 nodes are 'control plane' nodes well the last two are worker nodes.

# WORK IN PROGRESS

---
- name: Initialize MicroK8s on the first control plane node
  hosts: k8s_control_plane[0] # user the first server in the list
  become: yes # becomes sudo user
  tasks:
    - name: Generate join command for all other nodes
      ansible.builtin.shell: microk8s add-node --format short  # Will generate join token command
      register: join_token_output # puts the join tokem command in a variable
      run_once: true


- name: Join remaining nodes to the cluster
  hosts: k8s_control_plane[1:], k8s_workers # hosts in inventory it will run on
  become: yes # becomes sudo user
  tasks:
    - name: Get join command from the first control plane node
      ansible.builtin.shell: microk8s add-node
      run_once: true
      register: join_token_output
      delegate_to: "{{ groups['k8s_control_plane'][0] }}"
      
    - name: Set join command as a fact
      ansible.builtin.set_fact:
        join_command_from_control_plane: "{{ join_token_output.stdout }}"
      run_once: true

    - name: Run join command on other control plane nodes
      ansible.builtin.shell: "{{ hostvars[inventory_hostname]['join_command_from_control_plane'] }}"
      when: inventory_hostname in groups['k8s_control_plane']

    - name: Run join command on dedicated worker nodes
      ansible.builtin.shell: "{{ hostvars[inventory_hostname]['join_command_from_control_plane'] }} --worker"
      when: inventory_hostname in groups['k8s_workers']


- name: Configure cluster add ons
  hosts: k8s_control_plane[0] # Run the command on the first node
  become: yes # become sudo user
  tasks:
    - name: Enable metrics-server add-on
      ansible.builtin.shell: microk8s enable metrics-server # run shell command to enable metrics-server addon
      run_once: true

    - name: Enable MetalLB add-on with IP address pool
      ansible.builtin.shell: microk8s enable metallb:10.0.100.2-10.0.100.35 # run shell command to enable metalLB with the default IP range
      run_once: true