# This is to build out the cluster and join up all the nodes as specified.
# The first 3 nodes are 'control plane' nodes well the last two are worker nodes.

# WORK IN PROGRESS

---
- name: Join remaining nodes to the cluster
  hosts: k8s_control_plane[1:], k8s_workers
  become: yes
  tasks:
    - name: Generate a fresh join token
      ansible.builtin.shell: microk8s add-node
      run_once: true
      delegate_to: "{{ groups['k8s_control_plane'][0] }}"
      register: new_token_output
      
    - name: Set the join command for the current host
      ansible.builtin.set_fact:
        join_command: "{{ new_token_output.stdout | regex_search('microk8s join .*') }}"

    - name: Run join command on other control plane nodes
      ansible.builtin.shell: "{{ join_command }}"
      when: inventory_hostname in groups['k8s_control_plane']

    - name: Run join command on dedicated worker nodes
      ansible.builtin.shell: "{{ join_command }} --worker"
      when: inventory_hostname in groups['k8s_workers']


- name: Configure cluster add ons
  hosts: k8s_control_plane[0] # Run the command on the first node
  become: yes # become sudo user
  tasks:
    - name: Enable metrics-server add-on
      ansible.builtin.shell: microk8s enable metrics-server # run shell command to enable metrics-server addon
      register: result
      failed_when: "'is already enabled' not in result.stdout and 'is already enabled' not in result.stderr and result.rc != 0"
      run_once: true

    - name: Enable MetalLB add-on with IP address pool
      ansible.builtin.shell: microk8s enable metallb:10.0.100.2-10.0.100.35 # run shell command to enable metalLB with the default IP range
      run_once: true