# This is to build out the cluster and join up all the nodes as specified.
# The first 3 nodes are 'control plane' nodes well the last two are worker nodes.

# WORK IN PROGRESS

---
# Play 1: Create the cluster
- name: Create the cluster
  hosts: k8s_control_plane[1:], k8s_workers
  become: yes
  serial: 1  # Tells the playbook to process each one individually and one at a time with a unique join token for each.
  tasks:
    - name: Generate a fresh join token for the current host
      ansible.builtin.shell: microk8s add-node
      run_once: true
      delegate_to: "{{ groups['k8s_control_plane'][0] }}"
      register: token_output

    - name: Run join command
      ansible.builtin.shell: "{{ token_output.stdout | regex_search('microk8s join .*') }} --worker"
      when: inventory_hostname in groups['k8s_workers']

    - name: Run join command for control plane
      ansible.builtin.shell: "{{ token_output.stdout | regex_search('microk8s join .*') }}"
      when: inventory_hostname in groups['k8s_control_plane']

# Play 2: Configure cluster add-ons
- name: Configure cluster add-ons
  hosts: k8s_control_plane[0]
  become: yes
  tasks:
    - name: Enable metrics-server add-on (idempotent)
      ansible.builtin.shell: microk8s enable metrics-server
      register: result
      failed_when: "'is already enabled' not in result.stderr and result.rc != 0"

    - name: Enable MetalLB add-on (idempotent)
      ansible.builtin.shell: microk8s enable metallb:10.0.100.2-10.0.100.35
      register: result
      failed_when: "'is already enabled' not in result.stderr and result.rc != 0"