# Ansible to mount the NFS share to the first node in the cluster
# Not needed for the cluster to function with deployment but may be for adding directories into the NFS share for new deployments

---
- name: Add NFS share to /etc/fstab and mount it
  hosts: k8s_control_plane
  become: yes
  tasks:
    - name: Ensure NFS share is present and mounted
      ansible.builtin.mount:
        src: 10.0.100.20:/mnt/storage_pool/microk8s  # target of the NFS share
        path: /mnt/microk8s  # Local Path on the server
        fstype: nfs
        opts: defaults
        state: mounted # Adds the entry to fstab AND executes 'mount -a'

    # Will created needed directories on NFS share for K8s deployments
    - name: Create required storage subdirectories on NFS share
      ansible.builtin.file:
        path: "/mnt/microk8s/{{ item }}"
        state: directory
        owner: 1000
        group: 1000
        mode: '0775'
      loop:
        - grafana
        - heimdall
        - homarr
        - influxdb
        - jellyfin
        - pihole
        - pihole-mgmt
        - plex
        - postgreshomarr
      run_once: true